Repository goonkiloz/AudioSun, pull requests merged in 2024-02, with the labels that each got.

#35 created models files.
  .env.example
  .gitignore
  Pipfile
  Pipfile.lock
  app/models/__init__.py
  app/models/album.py
  app/models/comment.py
  app/models/db.py
  app/models/like.py
  app/models/playlist.py
  app/models/song.py
  app/models/user.py
  app/seeds/__init__.py
  app/seeds/users.py
  instance/dev.db
  migrations/README
  migrations/alembic.ini
  migrations/versions/20201120_150602_create_users_table.py
  migrations/versions/e94c9e913dec_.py
Labels: good first issue

#42 created seed for likes, edited song model and remigrate the tables.
  app/models/song.py
  app/seeds/__init__.py
  app/seeds/likes.py
  app/seeds/playlist_songs.py
  instance/dev.db
  migrations/versions/96a769114b4a_.py
Labels: good first issue

#46 Completed get all songs route
  app/__init__.py
  app/api/song_routes.py
  app/forms/__init__.py
  app/forms/new_song_form.py
Labels: enhancement

#47 revise comment model, add seeds and remigrate
  app/models/comment.py
  app/seeds/__init__.py
  app/seeds/comments.py
  app/seeds/playlist_songs.py
  instance/dev.db
  migrations/versions/34dc38f93a75_.py
Labels: good first issue

#50 Eddie dev
  app/__init__.py
  app/api/comments_routes.py
  app/api/song_routes.py
  app/forms/__init__.py
  app/forms/new_comment_form.py
  app/models/comment.py
  app/models/like.py
  app/seeds/likes.py
  instance/dev.db
Labels: good first issue

#53 Eddie dev
  app/__init__.py
  app/api/comments_routes.py
  app/api/playlist_routes.py
  app/api/song_routes.py
Labels: enhancement, good first issue

#58 finished playlist route.
  app/api/comments_routes.py
  app/api/playlist_routes.py
  app/models/playlist.py
Labels: good first issue

#62 revised add a song to playlist return.
  app/api/comments_routes.py
  app/api/playlist_routes.py
  instance/dev.db
Labels: enhancement

#64 tested all songs routes successfully after edits
  API.md
  app/api/song_routes.py
  instance/dev.db
  react-vite/src/Screens/Global/Navigation/Components/Navigation.jsx
  react-vite/src/Screens/Global/Navigation/Navigation.css
  react-vite/src/Screens/Global/OpenModalButton/OpenModalButton.jsx
  react-vite/src/Screens/Global/OpenModalButton/OpenModalMenuItem.jsx
  react-vite/src/Screens/Global/OpenModalButton/index.js
  react-vite/src/Screens/Global/ProfileButton.jsx
  react-vite/src/Screens/Login/LoginFormModal/LoginForm.css
  react-vite/src/Screens/Login/LoginFormModal/LoginFormModal.jsx
  react-vite/src/Screens/Login/LoginFormModal/index.js
  react-vite/src/Screens/Login/LoginFormPage/LoginForm.css
  react-vite/src/Screens/Login/LoginFormPage/LoginFormPage.jsx
  react-vite/src/Screens/Login/LoginFormPage/index.js
  react-vite/src/Screens/Signup/SignupFormModal/SignupForm.css
  react-vite/src/Screens/Signup/SignupFormModal/SignupFormModal.jsx
  react-vite/src/Screens/Signup/SignupFormModal/index.js
  react-vite/src/Screens/Signup/SignupFormPage/SignupForm.css
  react-vite/src/Screens/Signup/SignupFormPage/SignupFormPage.jsx
  react-vite/src/Screens/Signup/SignupFormPage/index.js
  react-vite/src/components/Navigation/index.js
Labels: enhancement

#71 Eddie dev
  instance/dev.db
  react-vite/src/Screens/Comments/AllComments/CommentsView.css
  react-vite/src/Screens/Comments/AllComments/CommentsView.jsx
  react-vite/src/Screens/Comments/NewComments/NewComment.css
  react-vite/src/Screens/Comments/NewComments/NewComment.jsx
  react-vite/src/Screens/Comments/RemoveCommentModal/RemoveCommentModal.css
  react-vite/src/Screens/Comments/RemoveCommentModal/RemoveCommentModal.jsx
  react-vite/src/Screens/Global/OpenModalButton/OpenModalButton.jsx
  react-vite/src/Screens/Songs/AllSongs/SingleSongView.jsx
  react-vite/src/Screens/Songs/AllSongs/SongsView.jsx
  react-vite/src/redux/comments.js
  react-vite/src/redux/store.js
  react-vite/src/router/index.jsx
Labels: good first issue

#72 started work on profile page
  react-vite/src/Screens/Global/ProfileButton.jsx
  react-vite/src/Screens/Profile/ProfileView.css
  react-vite/src/Screens/Profile/ProfileView.jsx
  react-vite/src/Screens/Profile/index.js
  react-vite/src/Screens/Songs/AllSongs/SingleSongView.jsx
  react-vite/src/Screens/Songs/AllSongs/SongsView.jsx
  react-vite/src/Screens/Songs/New Song/NewSongForm.jsx
  react-vite/src/redux/songs.js
  react-vite/src/router/index.jsx
Labels: enhancement

#95 Eddie dev
  .gitignore
  react-vite/src/Screens/Comments/AllComments/CommentsView.jsx
  react-vite/src/Screens/Comments/EditCommentModal/EditCommentModal.css
  react-vite/src/Screens/Comments/EditCommentModal/EditCommentModal.jsx
  react-vite/src/Screens/Comments/NewComments/NewComment.jsx
  react-vite/src/redux/comments.js
Labels: good first issue

#97 added modal for deleting songs. Have errors
  react-vite/dist/assets/index-570d6665.js
  react-vite/dist/assets/index-85afb02c.js
  react-vite/dist/index.html
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.jsx
  react-vite/src/Screens/Songs/DeleteSong/DeleteSongModal.jsx
  react-vite/src/Screens/Songs/Edit Song/index.js
  react-vite/src/redux/songs.js
Labels: help wanted

#98 revise model for songs to allow casacade delete on comments and like.…
  app/models/song.py
  migrations/versions/9360df7957bf_.py
  react-vite/src/Screens/Comments/AllComments/CommentsView.jsx
Labels: enhancement

#106 Eddie dev
  app/api/comments_routes.py
  app/api/song_routes.py
  app/forms/new_comment_form.py
  app/models/comment.py
  react-vite/src/Screens/Comments/AllComments/CommentsView.jsx
  react-vite/src/Screens/Comments/NewComments/NewComment.jsx
  react-vite/src/Screens/Comments/RemoveCommentModal/RemoveCommentModal.jsx
  react-vite/src/Screens/Likes/AllLikes/AllLikes.css
  react-vite/src/Screens/Likes/AllLikes/AllLikesView.jsx
  react-vite/src/Screens/Likes/AllLikes/LikeOrDislike.jsx
  react-vite/src/Screens/Songs/AllSongs/SingleSongPage.jsx
  react-vite/src/redux/comments.js
  react-vite/src/redux/likes.js
  react-vite/src/redux/store.js
Labels: good first issue

#110 Eddie dev
  app/__init__.py
  app/api/like_routes.py
  app/api/playlist_routes.py
  app/api/song_routes.py
  react-vite/src/Screens/Comments/AllComments/CommentsView.jsx
  react-vite/src/Screens/Comments/RemoveCommentModal/RemoveCommentModal.jsx
  react-vite/src/Screens/Likes/AllLikes/AllLikes.css
  react-vite/src/Screens/Likes/AllLikes/AllLikesView.jsx
  react-vite/src/Screens/Likes/AllLikes/LikeOrDislike.jsx
  react-vite/src/Screens/Likes/AllLikes/LikeOrRemoveLike.jsx
  react-vite/src/Screens/Songs/AllSongs/SingleSongPage.jsx
  react-vite/src/redux/comments.js
  react-vite/src/redux/likes.js
  react-vite/src/redux/playlists.js
  react-vite/src/redux/store.js
Labels: enhancement, good first issue

#111 fixed AWS errors and refactored Song CRUD
  app/api/aws_helpers.py
  app/api/song_routes.py
  app/forms/new_song_form.py
  react-vite/src/Screens/Player/DisplayTrack.jsx
  react-vite/src/Screens/Player/Player.jsx
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.jsx
  react-vite/src/Screens/Songs/New Song/NewSongForm.jsx
  react-vite/src/redux/queue.js
  react-vite/src/redux/store.js
  react-vite/src/router/Layout.jsx
Labels: enhancement

#125 Changed seeders for songs to be actual songs from aws
  app/api/aws_helpers.py
  app/forms/new_playlist_form.py
  app/forms/new_song_form.py
  app/seeds/songs.py
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.jsx
  react-vite/src/Screens/Songs/AllSongs/SongsView.jsx
  react-vite/src/Screens/Songs/Edit Song/EditSongModal.jsx
  react-vite/src/Screens/Songs/New Song/NewSongForm.jsx
Labels: enhancement

#131 Eddie dev
  app/forms/new_comment_form.py
  react-vite/src/Screens/Comments/EditCommentModal/EditCommentModal.css
  react-vite/src/Screens/Comments/EditCommentModal/EditCommentModal.jsx
  react-vite/src/Screens/Comments/NewComments/NewComment.jsx
  react-vite/src/redux/comments.js
Labels: enhancement

#138 rewrite err handling for singlesong thunk and navigate to 404 with
  app/api/song_routes.py
  app/forms/new_comment_form.py
  react-vite/src/Screens/NotFound/NotFoundPage.jsx
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.jsx
  react-vite/src/Screens/Songs/AllSongs/SingleSongPage.jsx
  react-vite/src/redux/songs.js
Labels: enhancement

#139 revise songs thunk handle to take rendering when a song is delete or …
  react-vite/src/Screens/Songs/AllSongs/SongsView.jsx
  react-vite/src/redux/songs.js
Labels: enhancement

#147 revise new song form to allow jpeg and remove demo seed info for play…
  app/forms/new_song_form.py
  app/seeds/playlists.py
  app/seeds/songs.py
Labels: enhancement

#157 Dev
  app/models/playlist.py
  app/seeds/songs.py
  react-vite/dist/assets/index-21821440.css
  react-vite/dist/assets/index-4f361ca4.js
  react-vite/dist/assets/index-c2b4528e.js
  react-vite/dist/assets/index-efbe6893.css
  react-vite/dist/index.html
  react-vite/dist/logo.png
  react-vite/index.html
  react-vite/public/logo.png
  react-vite/src/Screens/Comments/EditCommentModal/EditCommentModal.jsx
  react-vite/src/Screens/Comments/NewComments/NewComment.css
  react-vite/src/Screens/Comments/NewComments/NewComment.jsx
  react-vite/src/Screens/Comments/RemoveCommentModal/RemoveCommentModal.jsx
  react-vite/src/Screens/Global/Navigation/Components/Navigation.css
  react-vite/src/Screens/Global/Navigation/Components/Navigation.jsx
  react-vite/src/Screens/Global/ProfileButton.css
  react-vite/src/Screens/Global/ProfileButton.jsx
  react-vite/src/Screens/Likes/AllLikes/AllLikes.css
  react-vite/src/Screens/Likes/AllLikes/AllLikesView.jsx
  react-vite/src/Screens/Likes/AllLikes/LikeOrRemoveLike.jsx
  react-vite/src/Screens/Login/LoginFormModal/LoginForm.css
  react-vite/src/Screens/Login/LoginFormModal/LoginFormModal.jsx
  react-vite/src/Screens/Playlist/AddSongModal/AddSongModal.css
  react-vite/src/Screens/Playlist/AddSongModal/AddSongModal.jsx
  react-vite/src/Screens/Playlist/AllPlaylists/PlaylistsView.jsx
  react-vite/src/Screens/Playlist/AllPlaylists/SinglePlaylistPage.jsx
  react-vite/src/Screens/Playlist/CreatePlaylist/CreatePlaylist.css
  react-vite/src/Screens/Playlist/CreatePlaylist/CreatePlaylistPage.jsx
  react-vite/src/Screens/Playlist/DeletePlaylist/DeletePlaylistModal.jsx
  react-vite/src/Screens/Playlist/EditPlaylist/EditPlaylistModal.jsx
  react-vite/src/Screens/Playlist/RemoveSongModal/RemoveSongModal.jsx
  react-vite/src/Screens/Signup/SignupFormModal/SignupFormModal.jsx
  react-vite/src/Screens/Songs/AllSongs/SingleSongPage.jsx
  react-vite/src/Screens/Songs/AllSongs/SongsView.css
  react-vite/src/Screens/Songs/DeleteSong/DeleteSongModal.jsx
  react-vite/src/Screens/Songs/Edit Song/EditSongModal.jsx
  react-vite/src/Screens/Songs/New Song/NewSongForm.jsx
  react-vite/src/index.css
  react-vite/src/router/index.jsx
Labels: enhancement

#168 beginning css work for song components
  app/seeds/songs.py
  react-vite/dist/assets/index-cf84c3c7.js
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.css
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.jsx
  react-vite/src/Screens/Songs/AllSongs/SongsView.css
  react-vite/src/Screens/Songs/AllSongs/SongsView.jsx
Labels: enhancement

#172 added play/pause function to song component, css work
  react-vite/dist/assets/index-9b134cc6.css
  react-vite/dist/assets/index-a3f0a801.js
  react-vite/dist/assets/index-b9810049.js
  react-vite/dist/assets/index-cf84c3c7.js
  react-vite/dist/assets/index-f43453ef.css
  react-vite/dist/index.html
  react-vite/src/Screens/Global/ProfileButton.css
  react-vite/src/Screens/Playlist/AllPlaylists/SinglePlaylistComponent.jsx
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.css
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.jsx
  react-vite/src/Screens/Songs/AllSongs/SongsView.jsx
Labels: enhancement

#171 Eddie dev
  react-vite/public/logo.png
  react-vite/src/Screens/Global/Navigation/Components/Navigation.css
  react-vite/src/Screens/Global/Navigation/Components/Navigation.jsx
  react-vite/src/Screens/Global/ProfileButton.css
  react-vite/src/Screens/Global/ProfileButton.jsx
  react-vite/src/Screens/Login/LoginFormModal/LoginForm.css
  react-vite/src/Screens/Login/LoginFormPage/LoginFormPage.jsx
  react-vite/src/Screens/Playlist/CreatePlaylist/CreatePlaylist.css
  react-vite/src/Screens/Playlist/CreatePlaylist/CreatePlaylistPage.jsx
  react-vite/src/Screens/Playlist/CurrentUserPlaylists/CurrentUserPlaylistsPage.css
  react-vite/src/Screens/Playlist/CurrentUserPlaylists/CurrentUserPlaylistsPage.jsx
  react-vite/src/Screens/Playlist/DeletePlaylist/DeletePlaylistModal.jsx
  react-vite/src/Screens/Profile/ProfileView.css
  react-vite/src/Screens/Profile/ProfileView.jsx
  react-vite/src/Screens/Signup/SignupFormModal/SignupForm.css
  react-vite/src/Screens/Signup/SignupFormModal/SignupFormModal.jsx
  react-vite/src/Screens/Signup/SignupFormPage/SignupFormPage.jsx
  react-vite/src/Screens/Songs/DeleteSong/DeleteSongModal.jsx
  react-vite/src/Screens/Songs/Edit Song/EditSongModal.jsx
  react-vite/src/Screens/Songs/New Song/NewSong.css
  react-vite/src/Screens/Songs/New Song/NewSongForm.jsx
  react-vite/src/index.css
  react-vite/src/router/index.jsx
Labels: enhancement

#173 changed css for songsview, conforming to other styling
  react-vite/src/Screens/Player/Player.css
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.css
  react-vite/src/Screens/Songs/AllSongs/SongsView.css
  react-vite/src/Screens/Songs/AllSongs/SongsView.jsx
Labels: enhancement

#175 fixed deleting song still playing bug
  react-vite/src/Screens/Player/DisplayTrack.jsx
  react-vite/src/Screens/Songs/DeleteSong/DeleteSongModal.jsx
Labels: enhancement

#176 removed unused variables in components and changed splash page
  react-vite/dist/assets/index-5fdaaa86.css
  react-vite/dist/assets/index-b9810049.js
  react-vite/dist/assets/index-f11332db.js
  react-vite/dist/assets/index-f43453ef.css
  react-vite/dist/index.html
  react-vite/dist/logo.png
  react-vite/src/Screens/Player/Controls.jsx
  react-vite/src/Screens/Player/Player.jsx
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.jsx
  react-vite/src/Screens/Songs/AllSongs/SingleSongPage.jsx
  react-vite/src/Screens/Songs/AllSongs/SongsView.jsx
  react-vite/src/Screens/Songs/DeleteSong/DeleteSongModal.jsx
  react-vite/src/Screens/Songs/Edit Song/EditSongModal.jsx
  react-vite/src/Screens/SplashPage/SplashPage.jsx
  react-vite/src/context/PlayerContext.jsx
Labels: enhancement

#179 Eddie dev
  react-vite/public/splash.png
  react-vite/src/Screens/Comments/AllComments/CommentsView.css
  react-vite/src/Screens/Comments/AllComments/CommentsView.jsx
  react-vite/src/Screens/Comments/NewComments/NewComment.css
  react-vite/src/Screens/Comments/NewComments/NewComment.jsx
  react-vite/src/Screens/Global/ProfileButton.css
  react-vite/src/Screens/Global/ProfileButton.jsx
  react-vite/src/Screens/Likes/AllLikes/AllLikes.css
  react-vite/src/Screens/Login/LoginFormModal/LoginForm.css
  react-vite/src/Screens/Login/LoginFormModal/LoginFormModal.jsx
  react-vite/src/Screens/Playlist/CurrentUserPlaylists/CurrentUserPlaylistsPage.css
  react-vite/src/Screens/Playlist/CurrentUserPlaylists/CurrentUserPlaylistsPage.jsx
  react-vite/src/Screens/Signup/SignupFormModal/SignupForm.css
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.jsx
  react-vite/src/Screens/Songs/AllSongs/SingleSongPage.css
  react-vite/src/Screens/Songs/AllSongs/SingleSongPage.jsx
  react-vite/src/Screens/SplashPage/SplashPage.css
  react-vite/src/Screens/SplashPage/SplashPage.jsx
Labels: enhancement

#184 changed song seeders to have individual new images
  app/seeds/songs.py
Labels: enhancement

#186 changed genre for adding and editing songs to select field
  app/forms/new_song_form.py
  react-vite/dist/assets/index-6c6ca9de.js
  react-vite/dist/index.html
  react-vite/src/Screens/Songs/Edit Song/EditSongModal.jsx
  react-vite/src/Screens/Songs/New Song/NewSongForm.jsx
Labels: enhancement

#188 fixed bug with new genre select field
  app/forms/edit_song_form.py
  app/forms/new_song_form.py
  react-vite/dist/assets/index-cec81682.js
  react-vite/dist/assets/index-d1fa4953.js
  react-vite/dist/index.html
Labels: enhancement

#198 fixed 404 error on songs when putting letters in url
  react-vite/src/Screens/Songs/AllSongs/SingleSongPage.jsx
  react-vite/src/redux/songs.js
  react-vite/src/router/index.jsx
Labels: enhancement

#201 changed css for need-to-login
  react-vite/dist/assets/index-20366514.css
  react-vite/dist/assets/index-8756c2a4.css
  react-vite/dist/assets/index-bde656d6.js
  react-vite/dist/index.html
  react-vite/src/Screens/Songs/AllSongs/SingleSongPage.jsx
  react-vite/src/Screens/Songs/New Song/NewSong.css
  react-vite/src/Screens/Songs/New Song/NewSongForm.jsx
Labels: enhancement
