Repository goonkiloz/AudioSun, pull requests merged in 2024-04, with the labels that each got.

#212 Eddie dev
  app/api/song_routes.py
  app/models/like.py
  react-vite/public/github.png
  react-vite/src/Screens/Likes/AllLikes/AllLikesView.jsx
  react-vite/src/Screens/Player/DisplayTrack.jsx
  react-vite/src/Screens/Player/Player.css
  react-vite/src/Screens/Player/Player.jsx
  react-vite/src/Screens/Playlist/AllPlaylists/PlaylistsView.css
  react-vite/src/Screens/Profile/ProfileView.css
  react-vite/src/Screens/Profile/ProfileView.jsx
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.css
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.jsx
Labels: enhancement

#219 Readme Change
  AudioSun.md
  CloneGuide.md
  README.md
Labels: documentation

#221 Push for greenlit
  AudioSun.md
  CloneGuide.md
  README.md
  app/api/song_routes.py
  app/models/like.py
  react-vite/dist/assets/index-1f39ecba.css
  react-vite/dist/assets/index-6ed3a0c6.js
  react-vite/dist/assets/index-9b5f3bae.js
  react-vite/dist/assets/index-ce07578f.css
  react-vite/dist/github.png
  react-vite/dist/index.html
  react-vite/public/github.png
  react-vite/src/Screens/Global/Navigation/Components/Navigation.css
  react-vite/src/Screens/Global/Navigation/Components/Navigation.jsx
  react-vite/src/Screens/Global/ProfileButton.jsx
  react-vite/src/Screens/Likes/AllLikes/AllLikesView.jsx
  react-vite/src/Screens/Player/Controls.jsx
  react-vite/src/Screens/Player/DisplayTrack.jsx
  react-vite/src/Screens/Player/Player.css
  react-vite/src/Screens/Player/Player.jsx
  react-vite/src/Screens/Player/ProgressBar.jsx
  react-vite/src/Screens/Playlist/AllPlaylists/PlaylistsView.css
  react-vite/src/Screens/Playlist/AllPlaylists/SinglePlaylistComponent.jsx
  react-vite/src/Screens/Playlist/AllPlaylists/SinglePlaylistPage.jsx
  react-vite/src/Screens/Profile/ProfileView.css
  react-vite/src/Screens/Profile/ProfileView.jsx
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.css
  react-vite/src/Screens/Songs/AllSongs/SingleSongComponent.jsx
  react-vite/src/Screens/Songs/AllSongs/SingleSongPage.jsx
  react-vite/src/Screens/SplashPage/SplashPage.css
  react-vite/src/context/PlayerContext.jsx
  react-vite/src/index.css
  react-vite/src/redux/queue.js
  react-vite/src/redux/store.js
  react-vite/src/router/Layout.jsx
Labels: documentation, enhancement

#222 Readme img and gif update
  README.md
  img/AudioSun.gif
  img/AudioSunLanding.png
  img/AudioSunLogin.png
  img/AudioSunPlaylistDetails.png
  img/AudioSunPlaylists.png
  img/AudioSunSongDetail.png
  img/AudioSunSongs.png
  img/NewSongPage.png
  img/PlaylistDetailPage.png
  img/Playlists.png
  img/SongDetailPage.png
  img/Songs.png
  img/SplashPage.png
  react-vite/src/Screens/Songs/New Song/NewSong.css
  react-vite/src/Screens/Songs/New Song/NewSongForm.jsx
Labels: documentation
